spring:
  application:
    name: alloy-price-calculator
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: asdfgLKJH1@
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/liquibase/changelog-master.xml
  cache:
    jcache:
      config: classpath:/config/ehcache.xml
  sql:
    init:
      platform: mysql